### ISSUE TITLE
sorry to bother and i want to know how to convert the cdr file to tiff file if u are available

### ISSUE THREAD

**Issue by KINPOKER** [jfk9w/hoarder#164]
Hi Igor~
I'm very sorry to bother you in this repository what has nothing to do with aconvert website. I would like to know something about aconvert.

I am learning graphics... I want to know what is the implementation path of converting the cdr of the aconvert website into the tiff format~ What's the format file selected as an intermediate product for conversion...? I tried to use libcdr and libtiff for conversion, but I found there seems like lack of api to support me to do this. If it is convenient for you, I want to learn the implementation idea of https://www.aconvert.com/cn/image/cdr-to-tiff/. 

Thanks a lot and sorry again.

chueng

**Comment by jfk9w** [comment]
@KINPOKER I have no idea what you're talking about. I am in no way affiliated with aconvert.com. I have a HTTP API client library for aconvert, but it is in another repo and not what you're looking for, it seems. I can't help you, sorry.
